### PR TITLE
fix: wrenched cable stacking

### LINKED ISSUE #795: Cable broken by a wrench are not stackable
### Describe the bug

It seems like they keep their connection components

### How can we reproduce this bug or crash?

1. place 3 cables in an L shape
2. break them with a wrench starting from the corner one
3. see that you have 2 stacks of cable which can't be merged
4. if you have advanced tooltips activated, you can also see that these unstackable cables have an extra component compared to cable broken by hand

### What Minecraft version is this happening on?

Minecraft 1.21.1

### What NeoForge or Fabric version is this happening on?

neoforge 21.1.93

### What Refined Storage version is this happening on?

2.0.0-milestone 4.12

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by lucasser**
fix #795

### CODE REVIEW

File: refinedstorage-common/src/main/java/com/refinedmods/refinedstorage/common/support/AbstractBaseBlock.java [hunk 1]
```diff
@@ -231,6 +235,21 @@ private boolean dismantle(final BlockState state,
...
         if (blockEntity != null) {
             blockEntity.saveToItem(stack, level.registryAccess());
+            final PatchedDataComponentMap components = (PatchedDataComponentMap) stack.getComponents();
+            CustomData.update(DataComponents.BLOCK_ENTITY_DATA, stack, tag -> {
+                tag.remove("Down");
+                tag.remove("Up");
+                tag.remove("West");
+                tag.remove("North");
+                tag.remove("South");
+                tag.remove("East");
```
Comment (raoulvdberge) [inline refinedstorage-common/src/main/java/com/refinedmods/refinedstorage/common/support/AbstractBaseBlock.java]: In `CableConnections`, add a static method `strip`  and start using constants in `CableConnections`

**Review by raoulvdberge — CHANGES_REQUESTED** [review]

**Comment by raoulvdberge** [comment]
Please rebase too

**Comment by raoulvdberge** [comment]
I've simplified the code a bit and rebased.

**Review by raoulvdberge — APPROVED** [review]

**Comment by lucasser** [comment]
This doesn't fix the issue, since wrenched cables have an empty blockEntityTag. That's why I had the if statement to completely remove it if it's a cable
